#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  zipkin:
    base-url: http://localhost:9411/  
server:
  port: ${customer.port} 
  
feign:
    hystrix:       # even if eclipse is complaining, this is required
        enabled: true     
---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_cust
    username: root
    password: test    
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true
 
    
---

spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_cust
    username: root
    password: test    
  
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true