#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
 
server:
  port: ${zuul.port} 

  
zuul:
  sensitive-headers: Cookie,Set-Cookie 

documentation: 
  swagger: 
    services:   
      - 
        name: inventory-service
        url: ${documentation.baseurl}:${zuul.port}/inventory-service/v2/api-docs
        version: 2.0
      - 
        name: customer-service
        url: ${documentation.baseurl}:${zuul.port}/customer-service/v2/api-docs
        version: 2.0
      - 
        name: invoice-service
        url: ${documentation.baseurl}:${zuul.port}/invoice-service/v2/api-docs
        version: 2.0      

---

spring:
  profiles: dev  
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true

documentation: 
  baseurl: http://localhost
    
---

spring:
  profiles: docker 
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true
documentation: 
  baseurl: http://localhost
    
